---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-config-collector
  namespace: openshift-config
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - pull-secret
  - support
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-config-collector
  namespace: openshift-config
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: Role
  name: openshift-config-collector
subjects:
- kind: ServiceAccount
  name: OPERATOR_SERVICE_ACCOUNT
  namespace: OPERATOR_NAMESPACE